// Generated by scripts/sync-from-monorepo.ts - do not edit here.
// Source of truth: anbaric-cli/src in the Anbaric platform monorepo.
import {mkdir, readFile, writeFile} from "node:fs/promises";
import {join} from "node:path";

type AppConfigValues = {
    name : string,
    internalPort : number,
};

const APP_NAME_PATTERN = /^[a-z0-9_-]+$/;

const isValidAppName = (name : string) : boolean => APP_NAME_PATTERN.test(name);

const configPath = (appDir : string) => join(appDir, ".anbaric", "app-config.json");

const AppConfig = {

    async load(appDir : string) : Promise<AppConfigValues | undefined> {
        const path = configPath(appDir);

        let contents : string;
        try {
            contents = await readFile(path, "utf8");
        } catch {
            return undefined;
        }

        let parsed : any;
        try {
            parsed = JSON.parse(contents);
        } catch {
            throw new Error(`${path} is not valid JSON`);
        }
        if (typeof parsed?.name !== "string" || !isValidAppName(parsed.name)) {
            throw new Error(`${path} needs a "name" of lowercase letters, digits, "-" or "_"`);
        }
        if (typeof parsed?.internalPort !== "number" || !Number.isInteger(parsed.internalPort) || parsed.internalPort <= 0) {
            throw new Error(`${path} needs a numeric "internalPort" (the port your app listens on) - run \`anbaric app configure\` to set it`);
        }
        return { name: parsed.name, internalPort: parsed.internalPort };
    },

    async save(appDir : string, config : AppConfigValues) : Promise<string> {
        await mkdir(join(appDir, ".anbaric"), { recursive: true });
        await writeFile(configPath(appDir), JSON.stringify(config, null, 2));
        return configPath(appDir);
    },

    async suggestedName(appDir : string) : Promise<string> {
        try {
            const manifest = JSON.parse(await readFile(join(appDir, "package.json"), "utf8"));
            const sanitized = String(manifest.name).toLowerCase().replace(/[^a-z0-9_-]/g, "-");
            return isValidAppName(sanitized) ? sanitized : "app";
        } catch {
            return "app";
        }
    },

};

export { AppConfig, isValidAppName };
export type { AppConfigValues };
