// Generated by scripts/sync-from-monorepo.ts - do not edit here.
// Source of truth: anbaric-cli/src in the Anbaric platform monorepo.
import {CliOptions} from "./CliConfig";
import {TokenSigner} from "./TokenSigner";

const API_PREFIX = "/api/v2";

class PlatformClient {

    constructor(private options : CliOptions) {}

    get platformUrl() : string {
        return this.options.platformUrl;
    }

    get tenant() : string | undefined {
        return this.options.tenant;
    }

    async get(path : string) : Promise<any> {
        return this.request("GET", path);
    }

    async post(path : string, body : unknown) : Promise<any> {
        return this.request("POST", path, JSON.stringify(body), "application/json");
    }

    async put(path : string, body : unknown) : Promise<any> {
        return this.request("PUT", path, JSON.stringify(body), "application/json");
    }

    async patch(path : string, body : unknown) : Promise<any> {
        return this.request("PATCH", path, JSON.stringify(body), "application/json");
    }

    async delete(path : string) : Promise<any> {
        return this.request("DELETE", path);
    }

    async postBinary(path : string, body : Buffer, contentType : string) : Promise<any> {
        return this.request("POST", path, new Uint8Array(body), contentType);
    }

    async stream(path : string, onChunk : (text : string) => void, signal? : AbortSignal) : Promise<void> {
        const headers : Record<string, string> = {};
        if (this.options.tenant) headers["x-anbaric-tenant"] = this.options.tenant;
        if (this.options.key) headers["authorization"] = `Bearer ${new TokenSigner(this.options.key).sign()}`;

        const response = await fetch(`${this.options.platformUrl}${API_PREFIX}${path}`, { method: "GET", headers, signal });
        if (this.deniedForAuthentication(response)) {
            throw new Error(`You're not signed in to ${this.options.platformUrl} - run \`anbaric login\` to authorize this terminal`);
        }
        if (!response.ok || !response.body) {
            const problem = await response.json().catch(() => ({}));
            throw new Error(problem.error ?? `GET ${path} failed with status ${response.status}`);
        }

        const decoder = new TextDecoder();
        for await (const chunk of response.body as unknown as AsyncIterable<Uint8Array>) {
            onChunk(decoder.decode(chunk, { stream: true }));
        }
    }

    private async request(method : string, path : string, body? : BodyInit, contentType? : string) : Promise<any> {
        const headers : Record<string, string> = {};
        if (contentType) headers["content-type"] = contentType;
        if (this.options.tenant) headers["x-anbaric-tenant"] = this.options.tenant;
        if (this.options.key) headers["authorization"] = `Bearer ${new TokenSigner(this.options.key).sign()}`;

        const response = await fetch(`${this.options.platformUrl}${API_PREFIX}${path}`, {
            method,
            headers,
            body,
            redirect: "manual",
        });
        if (this.deniedForAuthentication(response)) {
            throw new Error(`You're not signed in to ${this.options.platformUrl} - run \`anbaric login\` to authorize this terminal`);
        }
        if (!response.ok) {
            const problem = await response.json().catch(() => ({}));
            throw new Error(problem.error ?? `${method} ${path} failed with status ${response.status}`);
        }
        if (response.status === 204) return undefined;
        return response.json();
    }

    private deniedForAuthentication(response : Response) : boolean {
        if (response.status === 401 || response.status === 403) return true;
        return response.status >= 300 && response.status < 400;
    }

}

export { PlatformClient }
