import {access, cp, mkdir, readFile, readdir, rm, writeFile} from "node:fs/promises";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

// This plugin is published from its own public repository, but two things in it
// are owned by the (private) platform monorepo: the reference docs and the
// handful of CLI client files the MCP server reuses. This copies both, so the
// monorepo stays the single source of truth and the plugin repo never diverges.
//
//   ANBARIC_MONOREPO=/path/to/monorepo npx tsx scripts/sync-from-monorepo.ts
//
// Defaults to a sibling checkout when the variable is unset.

const here = dirname(fileURLToPath(import.meta.url));
const pluginRoot = join(here, "..", "plugins", "anbaric");
const monorepo = process.env.ANBARIC_MONOREPO ?? join(here, "..", "..");

const GENERATED_HEADER = "// Generated by scripts/sync-from-monorepo.ts - do not edit here.\n" +
    "// Source of truth: anbaric-cli/src in the Anbaric platform monorepo.\n";

const CLIENT_FILES = ["PlatformClient", "TokenSigner", "CliConfig", "AppConfig"];

// Bundled into the MCP as a string so the server can hand it to an agent without
// reading anything off disk at run time.
const GUIDANCE_DOC = ["patterns", "ux-practices.md"];

/* Checked before anything is removed: pointed at the wrong directory, this
   used to clear the reference docs and then fail to find their replacement,
   leaving the skill with no docs at all. */
const mustExist = async (path : string, what : string) => {
    await access(path).catch(() => {
        throw new Error(`Cannot find ${what} at ${path} - set ANBARIC_MONOREPO to the platform monorepo`);
    });
};

const syncDocs = async () => {
    const source = join(monorepo, "anbaric", "docs");
    const destination = join(pluginRoot, "skills", "anbaric", "reference");
    await mustExist(source, "the platform docs");
    await rm(destination, { recursive: true, force: true });
    await cp(source, destination, { recursive: true });
    const files = await readdir(destination, { recursive: true });
    return files.filter(name => typeof name === "string" && name.endsWith(".md")).length;
};

const syncClient = async () => {
    const source = join(monorepo, "anbaric-cli", "src");
    const destination = join(pluginRoot, "mcp", "src", "platform");
    await mustExist(source, "the CLI source");
    await mkdir(destination, { recursive: true });
    for (const name of CLIENT_FILES) {
        const contents = await readFile(join(source, `${name}.ts`), "utf8");
        await writeFile(join(destination, `${name}.ts`), GENERATED_HEADER + contents);
    }
    return CLIENT_FILES.length;
};

const syncGuidance = async () => {
    const doc = await readFile(join(monorepo, "anbaric", "docs", ...GUIDANCE_DOC), "utf8");
    const module = `${GENERATED_HEADER.replace("anbaric-cli/src", `anbaric/docs/${GUIDANCE_DOC.join("/")}`)}
const UX_GUIDANCE = ${JSON.stringify(doc)};

export {UX_GUIDANCE};
`;
    await writeFile(join(pluginRoot, "mcp", "src", "guidance.ts"), module);
};

const sync = async () => {
    const docs = await syncDocs();
    const client = await syncClient();
    await syncGuidance();
    console.log(`Synced ${docs} docs, ${client} client files and the UX guidance from ${monorepo}`);
    console.log("Now rebuild the MCP bundle: (cd plugins/anbaric/mcp && npm run bundle)");
};

sync().catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
});
